### PR TITLE
Update gitignore

### PR DESCRIPTION
**Pull request by absarrahman**
Signed-off-by: absarrahman <raman040635@gmail.com>

### CODE REVIEW

**Comment by AmolGangadhare** [comment]
Hi,

Thanks for the PR. But what is this PR for?

Thanks

**Comment by absarrahman** [comment]
Cause if someone clones your repo, IDE related dependencies also gets
merged which breaks the VCS of the project. That's why I added it.

**Comment by prateekmedia** [comment]
Looks like you also removed funding.yml and other files in .github folder

**Comment by absarrahman** [comment]
> Looks like you also removed funding.yml and other files in .github folder

Cause it will create conflicts with other people. And .github folder automatically sets based on the user. Everyone has different .github folder.

**Comment by prateekmedia** [comment]
> > Looks like you also removed funding.yml and other files in .github folder
> 
> Cause it will create conflicts with other people after cloning. And .github folder automatically sets based on the user. Everyone has different .github folder.

Wow just wow, looks like you are having incorrect info or misconfusion b/w .github folder as it doesnt have different files for every other clones or forks.

If you look closely what you have deleted, you will find you have deleted Funding.yml which is used for sponsoring the project, reference below:




And you have deleted bug report and feature report md files which are used as a base template when creating a new issue, reference below:




I am not judging you or have any personal war but I am only saying that you should not have .github folder.

**Review by prateekmedia — CHANGES_REQUESTED** [review]
Do not remove .github folder files, as it contained funding info and issue templates.

**Comment by absarrahman** [comment]
I am so sorry :( Forgive me for this mistake. I really did not want to
cause any inconvenience.

**Pull request closed without merging**
