### PR TITLE
fixed NPE crash

### PR DESCRIPTION
**Pull request by tudorilisoi**
Fixed crash in development mode (VS Code)
Flutter v1.17.5
Dart SDK version: 2.12.1 (stable) on "linux_x64"

### CODE REVIEW

**Comment by vinicmg** [comment]
Worked on Pixel 4a Android 12
Flutter v2.0.1
Dart SDK Version: 2.12.0 (stable) on "windows_x64"

**Review by loddewijkxgust — APPROVED** [review]

**Review by AmolGangadhare — APPROVED** [review]
LGTM

**Comment by AmolGangadhare** [comment]
Thanks for improving the plugin. Looking forward to see many more :-)!

**Comment by The-Redhat** [comment]
Hey @ahmadjehad , It would be nice if you could merge this pr to the null-safe branch as well.

**Pull request merged**
